In [35]:
# loading libraries
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler # to handle the categorical data 
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

In [2]:
# data loading 
df=pd.read_csv(r"C:\Users\INDIAN\Downloads\car_price_prediction\cardekho.csv")
df.head()

                           name  year  selling_price  km_driven  ... mileage(km/ltr/kg)  engine max_power seats
0        Maruti Swift Dzire VDI  2014         450000     145500  ...              23.40  1248.0        74   5.0
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  ...              21.14  1498.0    103.52   5.0
2      Honda City 2017-2020 EXi  2006         158000     140000  ...              17.70  1497.0        78   5.0
3     Hyundai i20 Sportz Diesel  2010         225000     127000  ...              23.00  1396.0        90   5.0
4        Maruti Swift VXI BSIII  2007         130000     120000  ...              16.10  1298.0      88.2   5.0

[5 rows x 12 columns]

In [3]:
# rename mileage(km/ltr/kg) to mileage

df.rename(columns={"mileage(km/ltr/kg)":"mileage"},inplace=True)

In [4]:
df.head()

                           name  year  selling_price  km_driven    fuel  ...         owner mileage  engine  max_power  seats
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel  ...   First Owner   23.40  1248.0         74    5.0
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel  ...  Second Owner   21.14  1498.0     103.52    5.0
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol  ...   Third Owner   17.70  1497.0         78    5.0
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel  ...   First Owner   23.00  1396.0         90    5.0
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol  ...   First Owner   16.10  1298.0       88.2    5.0

[5 rows x 12 columns]

In [6]:
# chk for the null values
df.isnull().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
seats            221
dtype: int64

In [9]:
df.dropna(inplace=True)

In [11]:
df.isnull().sum(),df.shape

(name             0
 year             0
 selling_price    0
 km_driven        0
 fuel             0
 seller_type      0
 transmission     0
 owner            0
 mileage          0
 engine           0
 max_power        0
 seats            0
 dtype: int64,
 (7907, 12))

In [14]:
# handling categorical data
# fuel	seller_type	transmission	owner
label=LabelEncoder()  # initialize label encoder 

df["fuel_encoded"]=label.fit_transform(df["fuel"])
var=dict(zip(df["fuel"],df["fuel_encoded"]))
var

{'Diesel': 1, 'Petrol': 3, 'LPG': 2, 'CNG': 0}

In [15]:
df["seller_type_encoded"]=label.fit_transform(df["seller_type"])
var1=dict(zip(df["seller_type"],df["seller_type_encoded"]))
var1

{'Individual': 1, 'Dealer': 0, 'Trustmark Dealer': 2}

In [16]:
df["transmission_encoded"]=label.fit_transform(df["transmission"])
var2=dict(zip(df["transmission"],df["transmission_encoded"]))
var2

{'Manual': 1, 'Automatic': 0}

In [17]:
df["owner_encoded"]=label.fit_transform(df["owner"])
var3=dict(zip(df["owner"],df["owner_encoded"]))
var3

{'First Owner': 0,
 'Second Owner': 2,
 'Third Owner': 4,
 'Fourth & Above Owner': 1,
 'Test Drive Car': 3}

In [18]:
df.head()

                           name  year  selling_price  ...  seller_type_encoded transmission_encoded owner_encoded
0        Maruti Swift Dzire VDI  2014         450000  ...                    1                    1             0
1  Skoda Rapid 1.5 TDI Ambition  2014         370000  ...                    1                    1             2
2      Honda City 2017-2020 EXi  2006         158000  ...                    1                    1             4
3     Hyundai i20 Sportz Diesel  2010         225000  ...                    1                    1             0
4        Maruti Swift VXI BSIII  2007         130000  ...                    1                    1             0

[5 rows x 16 columns]

In [19]:
# dropping orignal columns

df.drop(columns=["name","fuel","seller_type","transmission","owner"],inplace=True)

In [20]:
df.head()

   year  selling_price  km_driven  mileage  ...  fuel_encoded seller_type_encoded  transmission_encoded  owner_encoded
0  2014         450000     145500    23.40  ...             1                   1                     1              0
1  2014         370000     120000    21.14  ...             1                   1                     1              2
2  2006         158000     140000    17.70  ...             3                   1                     1              4
3  2010         225000     127000    23.00  ...             1                   1                     1              0
4  2007         130000     120000    16.10  ...             3                   1                     1              0

[5 rows x 11 columns]

In [24]:
#feature selection
x=df.drop(columns=["selling_price","max_power"])
y=df["selling_price"]
x.head()

   year  km_driven  mileage  engine  seats  fuel_encoded  seller_type_encoded  transmission_encoded  owner_encoded
0  2014     145500    23.40  1248.0    5.0             1                    1                     1              0
1  2014     120000    21.14  1498.0    5.0             1                    1                     1              2
2  2006     140000    17.70  1497.0    5.0             3                    1                     1              4
3  2010     127000    23.00  1396.0    5.0             1                    1                     1              0
4  2007     120000    16.10  1298.0    5.0             3                    1                     1              0

In [25]:
# data splitting 

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [36]:
# model selection 
model=LinearRegression()
model2=RandomForestRegressor(max_depth=5,n_estimators=200,random_state=42)

# model fit 
model2.fit(x_train,y_train)

RandomForestRegressor(max_depth=5, n_estimators=200, random_state=42)

In [37]:
# model testing 
y_pred=model2.predict(x_test)
r2_score(y_test,y_pred)

0.9295881642227395

In [38]:
# traing accuracy 
y_pred=model2.predict(x_train)
r2_score(y_train,y_pred)

0.9193492192275718

In [39]:
# data scaling 
scalar=StandardScaler()

x_train_scaled=scalar.fit_transform(x_train)
x_test_scaled=scalar.transform(x_test)  # will do transfrom on test data to avoid data leakeage

In [40]:
# model traing on scaled data 
model2.fit(x_train_scaled,y_train)

RandomForestRegressor(max_depth=5, n_estimators=200, random_state=42)

In [42]:
# model testing 
y_pred=model2.predict(x_test_scaled)
r2_score(y_test,y_pred)

0.9295884988973647

In [44]:
# traing data 
y_pred=model2.predict(x_train_scaled)
r2_score(y_train,y_pred)

0.9193636865579683